apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-secret-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: postgres-sa
  namespace: dev
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
